from datetime import date
from decimal import Decimal
from typing import Optional, List

from sqlalchemy import ForeignKey, String, Numeric, Date, Integer, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship
from backend.database import Base # Ensure your Base is configured using AsyncAttrs (see below)
from pgvector.sqlalchemy import Vector

class Product(Base):
    __tablename__ =  "products"
    
    product_id: Mapped[int] = mapped_column(primary_key=True)
    product_name: Mapped[str] = mapped_column(String(100))
    product_author: Mapped[str] = mapped_column(String(100))
    product_price: Mapped[Decimal] = mapped_column(Numeric(precision=10, scale=2))
    product_stock: Mapped[int] = mapped_column(Integer)
    description: Mapped[Optional[str]] = mapped_column(String(1000), nullable=True)
    product_embedding: Mapped[Optional[list[float]]] = mapped_column("embedding", Vector(768), nullable=True)
    order_items: Mapped[List["Order"]] = relationship(back_populates="product_item", lazy="selectin")
    reviews: Mapped[List["Review"]] = relationship(back_populates="product", lazy="selectin")


class Order(Base): 
    __tablename__ = "orders"
    
    order_id: Mapped[int] = mapped_column(primary_key=True)
    product_id: Mapped[int] = mapped_column(ForeignKey("products.product_id"))
    order_name: Mapped[str] = mapped_column(String(100))
    order_date: Mapped[date] = mapped_column(Date, default=date.today)
    total_amount: Mapped[Decimal]= mapped_column(Numeric(precision=10, scale=2))
    order_quantity: Mapped[int]= mapped_column(Integer)
    order_status: Mapped[str] = mapped_column(String(100))
    
    product_item: Mapped["Product"] = relationship(back_populates="order_items", lazy="selectin")


class User(Base):
    __tablename__ = "users"
    
    # This ID will match the UUID generated by Supabase Auth
    id: Mapped[str] = mapped_column(String, primary_key=True) 
    email: Mapped[Optional[str]] = mapped_column(String(255), unique=True, nullable=True)
    username: Mapped[Optional[str]] = mapped_column(String(50), unique=True, nullable=True)
    
    reviews: Mapped[List["Review"]] = relationship(back_populates="user", lazy="selectin")


class Review(Base):
    __tablename__ = "reviews"
    
    id: Mapped[int] = mapped_column(primary_key=True)
    product_id: Mapped[int] = mapped_column(ForeignKey("products.product_id"))
    user_id: Mapped[str] = mapped_column(ForeignKey("users.id"))
    review_text: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    
    user: Mapped["User"] = relationship(back_populates="reviews", lazy="selectin")
    product: Mapped["Product"] = relationship(back_populates="reviews", lazy="selectin")