from sqlalchemy import ForeignKey, Column, Integer, String, Numeric, Date, DateTime
from datetime import date
from decimal import Decimal
from typing import Optional
from sqlalchemy.orm import Mapped, mapped_column, relationship
from backend.database import Base
from pgvector.sqlalchemy import Vector

class Product(Base):
    __tablename__ =  "products" #products here
    product_id: Mapped[int] = mapped_column(primary_key = True)
    product_name: Mapped[str] = mapped_column(String(100))
    product_author: Mapped[str] = mapped_column(String(100))
    product_price: Mapped[Decimal] = mapped_column(Numeric(precision=10, scale=2))
    product_stock: Mapped[int] = mapped_column(Integer)
    description: Mapped[Optional[str]] = mapped_column(String(1000), nullable=True)
    product_embedding: Mapped[Optional[list[float]]] = mapped_column("embedding", Vector(768), nullable=True)

    order_item: Mapped[list["Order"]] = relationship(back_populates="product_item")


class Order(Base): 
    __tablename__ = "orders" #orders here
    order_id: Mapped[int] = mapped_column(primary_key = True)
    product_id: Mapped[int] = mapped_column(Integer, ForeignKey("products.product_id"))
    order_name: Mapped[str] = mapped_column(String(100))
    order_date: Mapped[date] = mapped_column(Date, default=date.today)
    total_amount: Mapped[Decimal]= mapped_column(Numeric(precision=10, scale=2))
    order_quantity: Mapped[int]= mapped_column(Integer)
    order_status: Mapped[str] = mapped_column(String(100))
    product_item: Mapped["Product"] = relationship(back_populates="order_item")

class User(Base):
    __tablename__ = "users"
    # This ID will match the UUID generated by Supabase Auth
    id = Column(String, primary_key=True) 
    email = Column(String(255), unique=True)
    username = Column(String(50), unique=True)
    reviews = relationship("Review", back_populates="user")

class Review(Base):
    __tablename__ = "reviews"
    id = Column(Integer, primary_key=True)
    product_id = Column(Integer, ForeignKey("products.product_id"))
    user_id = Column(String, ForeignKey("users.id"))
    review_text = Column(Text)
    user = relationship("User", back_populates="reviews")
    product = relationship("Product") # Assuming Product is your book table